version: '3.8'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: simple_bank
    ports:
      - "5434:5432"
    networks:
      - simplebank-network

  simplebank:
    image: simplebank:latest
    depends_on:
      - postgres
    environment:
      DB_DRIVER: postgres
      DB_SOURCE: postgresql://root:mysecretpassword@postgres:5432/simple_bank?sslmode=disable
      SERVER_ADDRESS: 0.0.0.0:8080
      TOKEN_SYMMETRIC_KEY: 12345678901234567890123456789012
      ACCESS_TOKEN_DURATION: 15m
    ports:
      - "8080:8080"
    networks:
      - simplebank-network

networks:
  simplebank-network:
    driver: bridge
