apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::730335262390:role/AWSEKSrole
      username: AWSEKSrole
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::529088290413:user/github-ci
      username: github-ci
      groups:
        - system:masters
